name: Astronomer CI - Deploy code to Cosmic Energy

on:
  pull_request:
    types:
      - closed
    branches: [deploy]

jobs:
  deploy:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    env:
      ## Sets Prod Deployment API credential as an environment variable
      ASTRO_API_TOKEN: ${{ secrets.PROD_ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.2
      with:
        deployment-id: ${{ vars.PROD_ASTRO_DEPLOYMENT_ID }}